---
- hosts: all
  gather_facts: yes
  tasks:
    - apt: update_cache=yes state=latest name='{{ item }}'
      with_items:
        - dnsmasq
        - nginx
        - syslinux
        - syslogd

    # Configure Dnsmasq
    - name: Configure Dnsmasq with /etc/dnsmasq.conf
      template: src=templates/etc/dnsmasq.conf dest=/etc/
      notify: Restart dnsmasq

    # Setup PXE
    - file: state=directory path=/var/lib/tftpboot/pxelinux.cfg/

    - copy: src=r29.png dest=/var/lib/tftpboot/
    - shell: cp /usr/lib/syslinux/pxelinux.0 /var/lib/tftpboot/ creates=/var/lib/tftpboot/pxelinux.0
    - shell: cp /usr/lib/syslinux/vesamenu.c32 /var/lib/tftpboot/ creates=/var/lib/tftpboot/vesamenu.c32

    - template: src=templates/var/lib/tftpboot/pxelinux.cfg/default dest=/var/lib/tftpboot/pxelinux.cfg/

    # Setup Kickstart file for Centos install
    - name: Install Centos Kickstart file
      template: src=templates/var/lib/tftpboot/centos7-ks.cfg dest=/var/lib/tftpboot/

    # Setup Install disk
    - name: Download Centos install disk
      get_url:
        dest=/srv/CentOS-7-x86_64-Minimal-1511.iso
        url=http://mirror.lug.udel.edu/pub/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso
        checksum=md5:88c0437f0a14c6e2c94426df9d43cd67
        backup=yes

    - name: Mount Centos install disk
      mount:
        name=/mnt
        src=/srv/CentOS-7-x86_64-Minimal-1511.iso
        fstype=iso9660
        state=mounted

    - shell: cp -R /mnt/* /var/lib/tftpboot/

    # Setup Nginx to serve the install disk
    - copy: dest=/etc/nginx/sites-available/pxe
      args:
        content: |
          server {
            listen   80;
            root /var/lib/tftpboot;
            server_name localhost;
          }
      notify: Restart nginx

    - file: state=link src=../sites-available/pxe path=/etc/nginx/sites-enabled/pxe
      notify: Restart nginx

    - file: state=absent path=/etc/nginx/sites-enabled/default
      notify: Restart nginx

  handlers:
    - name: Restart dnsmasq
      service:  name=dnsmasq state=restarted
    - name: Restart nginx
      service: name=nginx state=restarted
