---
- hosts: all
  gather_facts: yes
  pre_tasks:
    - apt: update_cache=yes state=latest name='{{ item }}'
      with_items:
        - dnsmasq
        - nginx
        - syslinux

    - copy: dest=/etc/dnsmasq.conf
      args:
        content: |
          port=0
          interface=eth1
          dhcp-range=192.168.42.10,192.168.42.20
          dhcp-boot=pxelinux.0
          dhcp-option=6,0.0.0.0,8.8.8.8
          dhcp-option-force=tag:bios,209,pxelinux.cfg/default
          pxe-service=tag:bios,x86PC,"x86 bios boot msg",pxelinux
          enable-tftp
          tftp-root=/var/lib/tftpboot

      notify: Restart dnsmasq

    - mount:
        name=/mnt
        src=/vagrant/CentOS-7-x86_64-Minimal-1511.iso
        fstype=iso9660
        state=mounted

    - file: state=directory path=/var/lib/tftpboot/pxelinux.cfg/

    - copy: dest=/var/lib/tftpboot/pxelinux.cfg/default
      args:
        content: |
          default vesamenu.c32
          prompt 0
          timeout 300
          menu title ########## PXE Boot Menu ##########
          label 1
          menu label ^1) Install CentOS 7 x64 from Kickstart
          kernel isolinux/vmlinuz
          append initrd=isolinux/initrd.img ks=http://192.168.42.2/centos7-ks.cfg
          label 2
          menu label ^2) Install CentOS 7 x64 with Local Repo
          kernel isolinux/vmlinuz
          append initrd=isolinux/initrd.img method=http://192.168.42.2/ devfs=nomount
          label 3
          menu label ^3) Boot from local drive

    - copy: dest=/var/lib/tftpboot/centos7-ks.cfg
      args:
        content: |
          install
          autostep
          reboot
          # System authorization information
          auth --enableshadow --passalgo=sha512
          # Use network installation
          url --url="http://192.168.42.2/"
          # Run the Setup Agent on first boot
          firstboot --enable
          ignoredisk --only-use=sda
          # Keyboard layouts
          keyboard --vckeymap=us --xlayouts='us'
          # System language
          lang en_US.UTF-8
          # Network information
          network  --bootproto=dhcp --device=enp0s8 --ipv6=auto --activate
          network  --hostname=localhost.localdomain
          # Root password
          rootpw --iscrypted $6$PlqMCtdIFl7gP4nH$fS1/2/BKGTA4Rw7rns/p.cStNzQFKuaRXPvhNbJjiL7hbo8YFyabNqFKCbOz.ZsH8/5iUiE7Bo67RiLgAniBU/
          # System timezone
          timezone America/New_York --isUtc
          # System bootloader configuration
          bootloader --append=" crashkernel=auto" --location=mbr --boot-drive=sda
          autopart --type=lvm
          # Partition clearing information
          clearpart --none --initlabel
          %packages
          @^minimal
          @core
          kexec-tools
          %end
          %addon com_redhat_kdump --enable --reserve-mb='auto'
          %end

    - shell: cp -R /mnt/* /var/lib/tftpboot/
    - shell: cp /usr/lib/syslinux/pxelinux.0 /var/lib/tftpboot/
    - shell: cp /usr/lib/syslinux/vesamenu.c32 /var/lib/tftpboot/

    - copy: dest=/etc/nginx/sites-available/pxe
      args:
        content: |
          server {
            listen   80;
            root /var/lib/tftpboot;
            server_name localhost pxe.local.rf29.net;
          }
      notify: Restart nginx

    - file: state=link src=../sites-available/pxe path=/etc/nginx/sites-enabled/pxe
      notify: Restart nginx

    - file: state=absent path=/etc/nginx/sites-enabled/default
      notify: Restart nginx

    - file: state=directory path=/srv/pxe

    - lineinfile: dest=/etc/hosts line='{{ guest_ip_address }} {{ guest_hostname }}'
      delegate_to: localhost
      become: yes

  handlers:
    - name: Restart dnsmasq
      service:  name=dnsmasq state=restarted
    - name: Restart nginx
      service: name=nginx state=restarted
