---
- hosts: all
  gather_facts: yes
  vars:
    dnsmasq_interface: eth1
    dnsmasq_dhcp_range: 192.168.42.10,192.168.42.20
    dnsmasq_router: 192.168.42.1
    dnsmasq_server: 8.8.8.8
    dnsmasq_only_known_hosts: no
    dnsmasq_hosts: []
    pxe_kickstart_host: 192.168.42.2
    kickstart_url: http://192.168.42.2
    kickstart_logging_host: 192.168.42.2
  tasks:
    - apt: update_cache=yes state=latest name='{{ item }}'
      with_items:
        - dnsmasq
        - nginx
        - syslinux
        - syslogd

    - template: dest=/etc/ src=templates/etc/dnsmasq.conf
      notify: Restart dnsmasq

    - get_url:
        dest=/srv/
        url=http://mirror.lug.udel.edu/pub/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso

    - mount:
        name=/mnt
        src=/srv/CentOS-7-x86_64-Minimal-1511.iso
        fstype=iso9660
        state=mounted

    - file: state=directory path=/var/lib/tftpboot/pxelinux.cfg/

    - copy: dest=/var/lib/tftpboot/pxelinux.cfg/default
      args:
        content: |
          default vesamenu.c32
          prompt 0
          timeout 50
          menu title ########## PXE Boot Menu ##########
          menu color screen 47 FFFFFFFF FFFFFFFF std
          label Centos 7 Kickstart install
            menu label ^1) Install CentOS 7 x64 from Kickstart
            kernel isolinux/vmlinuz
            append initrd=isolinux/initrd.img ks=http://{{ pxe_kickstart_host }}/centos7-ks.cfg
          label Centos 7 Gui install
            menu label ^2) Install CentOS 7 x64 with Local Repo
            kernel isolinux/vmlinuz
            append initrd=isolinux/initrd.img method=http://{{ pxe_kickstart_host }}/ devfs=nomount
          label local
            menu label ^3) Boot from local drive

    - copy: dest=/var/lib/tftpboot/centos7-ks.cfg
      args:
        content: |
          auth --passalgo=sha512
          autostep
          bootloader --append=" crashkernel=auto" --location=mbr --boot-drive=sda
          text
          install
          keyboard --vckeymap=us --xlayouts='us'
          lang en_US.UTF-8
          logging --host={{ kickstart_logging_host }} --level info
          network --activate --bootproto=dhcp --device=enp11s0 --ipv6=auto --activate
          reboot
          rootpw --iscrypted $6$PlqMCtdIFl7gP4nH$fS1/2/BKGTA4Rw7rns/p.cStNzQFKuaRXPvhNbJjiL7hbo8YFyabNqFKCbOz.ZsH8/5iUiE7Bo67RiLgAniBU/
          selinux --disabled
          skipx
          timezone America/New_York --isUtc
          url --url={{ kickstart_url }}
          %packages
          @^minimal
          @core
          kexec-tools
          %end
          %addon com_redhat_kdump --enable --reserve-mb='auto'
          %end

    - copy: src=r29.png dest=/var/lib/tftpboot/

    - shell: cp -R /mnt/* /var/lib/tftpboot/
    - shell: cp /usr/lib/syslinux/pxelinux.0 /var/lib/tftpboot/
    - shell: cp /usr/lib/syslinux/vesamenu.c32 /var/lib/tftpboot/

    - copy: dest=/etc/nginx/sites-available/pxe
      args:
        content: |
          server {
            listen   80;
            root /var/lib/tftpboot;
            server_name localhost;
          }
      notify: Restart nginx

    - file: state=link src=../sites-available/pxe path=/etc/nginx/sites-enabled/pxe
      notify: Restart nginx

    - file: state=absent path=/etc/nginx/sites-enabled/default
      notify: Restart nginx

    - file: state=directory path=/srv/pxe

  handlers:
    - name: Restart dnsmasq
      service:  name=dnsmasq state=restarted
    - name: Restart nginx
      service: name=nginx state=restarted
